name: ez_booking
description: "ez_booking"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.3.0
  gap: ^3.0.1
  responsive_sizer: ^3.3.1
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  flutter_otp_text_field: ^1.2.0
  get: ^4.6.6
  http: ^1.2.2
  carousel_slider: ^5.0.0
  pin_code_fields: ^8.0.1
  snapping_page_scroll: ^3.1.0
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  flutter_animate: ^4.5.2
  flutter_spinkit: ^5.2.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  razorpay_flutter: ^1.3.7
  buttons_tabbar: ^1.3.14
  google_nav_bar: ^5.0.7
  geocoding: ^3.0.0
  easy_stepper: ^0.8.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon/
    - assets/onboarding/
    - assets/appImages/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/font/Lexend-Regular.ttf
          weight: 400
        - asset: assets/font/Lexend-Light.ttf
          weight: 300
        - asset: assets/font/Lexend-Bold.ttf
          weight: 700
        - asset: assets/font/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/font/Lexend-Medium.ttf
          weight: 500
